#!/usr/bin/env zsh

# XDG
export XDG_CONFIG_HOME=$HOME/.config

# editor
export EDITOR="vim"
export VISUAL=$EDITOR

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
